package com.github.mkopylec.projectmanager.core.team;

enum ErrorCode {

    EMPTY_TEAM_NAME,
    TEAM_ALREADY_EXISTS,
    MISSING_TEAM,
    EMPTY_MEMBER,
    EMPTY_MEMBER_FIRST_NAME,
    EMPTY_MEMBER_LAST_NAME,
    EMPTY_MEMBER_JOB_POSITION,
    INVALID_MEMBER_JOB_POSITION
}
