package com.github.mkopylec.projectmanager.project;

enum ErrorCode {

    UNEXPECTED_ERROR,
    EMPTY_PROJECT_IDENTIFIER,
    EMPTY_PROJECT_NAME,
    EMPTY_FEATURE,
    EMPTY_FEATURE_NAME,
    EMPTY_FEATURE_STATUS,
    EMPTY_FEATURE_REQUIREMENT,
    NO_PROJECTS_EXIST,
    NONEXISTENT_PROJECT,
    PROJECT_ALREADY_STARTED,
    UNSTARTED_PROJECT,
    PROJECT_ALREADY_ENDED,
    PROJECT_ENDING_CONDITION_NOT_FULFILLED
}
