package com.github.mkopylec.projectmanager.core.project;

enum ErrorCode {

    EMPTY_PROJECT_IDENTIFIER,
    EMPTY_PROJECT_NAME,
    EMPTY_FEATURE,
    EMPTY_FEATURE_NAME,
    EMPTY_FEATURE_STATUS,
    INVALID_FEATURE_STATUS,
    EMPTY_FEATURE_REQUIREMENT,
    INVALID_FEATURE_REQUIREMENT,
    MISSING_PROJECT,
    PROJECT_ALREADY_STARTED,
    UNSTARTED_PROJECT,
    PROJECT_ALREADY_ENDED,
    PROJECT_ENDING_CONDITION_NOT_FULFILLED,
    UNASSIGNED_TEAM
}
