package com.github.mkopylec.projectmanager.domain.exceptions;

public enum ErrorCode {

    UNEXPECTED_ERROR,
    EMPTY_TEAM_NAME,
    TEAM_ALREADY_EXISTS,
    NONEXISTENT_TEAM,
    EMPTY_MEMBER,
    EMPTY_MEMBER_FIRST_NAME,
    EMPTY_MEMBER_LAST_NAME,
    EMPTY_MEMBER_JOB_POSITION,
    INVALID_MEMBER_JOB_POSITION,
    EMPTY_PROJECT_IDENTIFIER,
    EMPTY_PROJECT_NAME,
    EMPTY_FEATURE,
    EMPTY_FEATURE_NAME,
    EMPTY_FEATURE_STATUS,
    INVALID_FEATURE_STATUS,
    EMPTY_FEATURE_REQUIREMENT,
    INVALID_FEATURE_REQUIREMENT,
    NONEXISTENT_PROJECT,
    PROJECT_ALREADY_STARTED,
    UNASSIGNED_TEAM
}
